### PR TITLE
New aside nav drawer

### PR DESCRIPTION
**Pull request by Talkingbaby**
I recreated a simpler nav drawer using bulma's panel classes for layout and styling. This template is very simple and can easily be modified to allow for more complex layouts. If a hero is wanted in the nav drawer I believe that can go in the panel-header or replace the panel header.

### CODE REVIEW

**Comment by dansup** [comment]
@Talkingbaby Hey, thanks for the PR. The template looks great!

I noticed that the  ```height: 50rem;``` on ```.column``` is causing an overflow. Can you fix that and I will be happy to merge.

screen shot 2017-12-05 at 8 51 59 pm

**Comment by Talkingbaby** [comment]
@dansup I changed the css to min-height: 100vh and it appears to be showing that way on github as well. Are you having issues still with that?

**Comment by dansup** [comment]
@Talkingbaby Try removing ```height``` and/or ```min-height``` on ```.columns```

**Comment by Talkingbaby** [comment]
@dansup I just made a pushed the change. I originally left the height since I liked the look lol.

**Comment by dansup** [comment]
@Talkingbaby Was your goal a fixed full-height aside with the content having a y-overflow? I think you can do that with a hero fullheight, I can merge this if you are ready.

**Comment by dansup** [comment]
@Talkingbaby I have an IRC channel for this repo on freenode if you want to discuss this there. [https://webchat.freenode.net/?channels=#bulma-templates](https://webchat.freenode.net/?channels=#bulma-templates)

**Comment by Talkingbaby** [comment]
@dansup you can merge. I had no preferences.

**Pull request merged**
