### PR TITLE
Added [personal/portfolio] template

### PR DESCRIPTION
**Pull request by mubaidr**
- [ ] Update template specific styles
- [x] Add basic template
- [ ] Review

This is still in progress, please don't merge it yet. This PR is for review purposes.

### CODE REVIEW

**Comment by diomed** [comment]
I'm unsure what @dansup thinks about self-promotion by putting your data everywhere in template, 
I kinda don't like it. Credits on bottom are fine, rest should be demo content, not links to your personal 
pages and your name. I did several of them, and never used my name.

Other than that - you should use link to Font Awesome 5 for new templates.

Those are some tips - I'll let @dansup decide on the first one, whether he'll allow it and merge like that or not. FontAwesome, however, you should correct.

**Comment by mubaidr** [comment]
Thanks for the review, its serves demo data purpose and that's the whole point of this review request. To improve it. 

I was using older html template and it has font awesome 4.5, will update it and add icons where required. 

Also please let me know if there should be any other section included too.

**Comment by mubaidr** [comment]
@diomed @dansup review requested, I think its good enough now.

**Comment by diomed** [comment]
It would look a bit better if card with profile and skills was below. 
if it had some margin and was not stickied to  green container above it, IMHO.

also, you tend to create a space via use of a lot of <br> tags.
I mean... not the happiest of solutions for a template. That's quick and dirty fix.
 It's better to use custom` margin-top ` or maybe even use flexbox's vertical centering https://github.com/jgthms/bulma/issues/1401

**Comment by mubaidr** [comment]
These sections are children to the about section, that is why I thought it would be good to group them into one. Lets hear some more reviews? 

Sure, these are just quick hacks, will remove these and update using CSS.

**Comment by diomed** [comment]
unsure what MSSQL is 😄 

probably a typo.

anyway, I have no other special reviews. if you think it's fine, it's fine, just fix what I suggested and maybe remove old version of font awesome, and you're good to go. it's your template. and looks good to me.

I'll just @GabMic here, if he has anything more to add, since you're basically closing his request.

**Comment by diomed** [comment]
thank you for your template.
you are most welcome to contribute further.

also, if you'd like your template to have screenshot, you could upload it to repository.
you can look what existing dimensions are.

**Comment by mubaidr** [comment]
Totally forgot about screenshot. Will do it. Thanks

**Comment by diomed** [comment]
uh-oh. I put a screenshot. lol 😋 
this can stay as it is for the time being, but it will probably be cut, eventually, if number of templates grows.

**Pull request merged**
